import hashlib,json
from pathlib import Path
import fitz
R=Path(__file__).resolve().parents[2];O=R/'skill_data';PDF=R/'Downloads/AS_166309_LJ-X8000_UM_N04GB_WW_GB_2036_1.pdf';DOC='KEYENCE-E3E51B234B56';SHA='e3e51b234b56ea11182e78b39574678f5c7244c65d6455664927f580dd1a47c3'
def put(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def main():
 if hashlib.sha256(PDF.read_bytes()).hexdigest()!=SHA:raise RuntimeError('source SHA mismatch')
 t=fitz.open(PDF)[378].get_text('text');b={'block_id':'MSB-LJX8000-379-X8900-SPECS','document_id':DOC,'source_sha256':SHA,'pdf_page_index':379,'printed_page':'10-5','bbox':None,'block_type':'specification_table','native_text_sha256':hashlib.sha256(t.encode()).hexdigest(),'visual_verification':True,'evidence_status':'DIRECT_VISUAL','fields_supported':['LJ-X series head specifications; model columns verified visually']};q=O/'evidence/manual_source_blocks';q.mkdir(parents=True,exist_ok=True);put(q/(b['block_id']+'.json'),b)
 e={'evidence_quality':'DIRECT_VISUAL','block_id':b['block_id'],'document_id':DOC,'source_sha256':SHA,'pdf_page_index':379,'printed_page':'10-5','evidence_excerpt_hash':b['native_text_sha256']}
 def n(v,u,condition):return {'value':v,'unit':u,'condition':condition,'mode':'2D','evidence':[e]}
 models=['LJ-X8020','LJ-X8030','LJ-X8060','LJ-X8070','LJ-X8080','LJ-X8100','LJ-X8200','LJ-X8300','LJ-X8400','LJ-X8900']
 heads=[{'head_id':'HEAD-'+m,'model':m,'head_family':'LJ-X Series','controller_family':'LJ-X8000','knowledge_status':'OFFICIAL_EXACT','source_evidence':[e]} for m in models]
 x={'head_id':'HEAD-LJ-X8900','model':'LJ-X8900','family':'LJ-X Series','compatible_controllers':[{'controller':'LJ-X8000','head':'HEAD-LJ-X8900','relation':'COMPATIBLE','mode':'2D','direct_evidence':[e]}],'optical_geometry':{'reference_distance':n(980,'mm','reference distance'),'measurement_distance_range':{'nearest_z':n(-400,'mm','relative to reference distance'),'reference_z':n(0,'mm','reference distance'),'farthest_z':n(400,'mm','relative to reference distance')},'z_range':n(800,'mm','full scale; +400 to -400 mm'),'x_range_at_near':n(300,'mm','near side'),'x_range_at_reference':n(510,'mm','reference distance'),'x_range_at_far':n(720,'mm','far side')},'sampling':{'profile_points':n(3200,'points','profile data count'),'x_resolution':n(200,'um','profile data interval X-axis width; from 100 um')},'metrology':{'repeatability_z':n(10,'um','standard object; average height of initial setting area with height/position tool; other initial settings'),'repeatability_x':n(25,'um','standard object; average height of initial setting area with height/position tool; other initial settings'),'linearity':{'value':None,'status':'NOT_VERIFIED'}},'optics':{'wavelength':n(405,'nm','visible light'),'laser_class':{'value':'Class 2M laser product','evidence':[e]}},'environment':{'protection_rating':{'value':'IP67 (IEC60529)','evidence':[e]},'operating_temperature':n('0 to +45','C','ambient temperature')},'installation':{'dead_zone':None,'mounting_distance':n(980,'mm','reference distance; surfaces must remain inside Â±400 mm Z envelope'),'interference_constraints':{'value':None,'status':'NOT_VERIFIED'}},'modes':['2D'],'limitations':['X width depends on Z position; use near/reference/far values, not a single FOV.'],'source_evidence':[e]}
 put(O/'hardware/head_specifications.yaml',{'heads':[x]});put(O/'hardware/controller_head_compatibility.yaml',{'relationships':x['compatible_controllers']+[{'controller':'LJ-X8000A','head':'HEAD-LJ-X8900','relation':'NOT_VERIFIED','mode':'unknown','direct_evidence':[]},{'controller':'LJ-S8000','head':'HEAD-LJ-X8900','relation':'NOT_VERIFIED','mode':'unknown','direct_evidence':[]}]})
 put(O/'hardware/head_capability_matrix.yaml',{'heads':models,'properties':{'LJ-X8900':{'controller_compatibility':'LJ-X8000 direct','2D':'SUPPORTED','3D':'NOT_VERIFIED','z_range':'800 mm full scale','x_width_near_reference_far':'300 / 510 / 720 mm','profile_points':3200,'accuracy_class':'repeatability Z 10 um; X 25 um with stated condition','speed_frequency':'NOT_VERIFIED'}}})
 put(O/'hardware/installation_envelopes.yaml',{'envelopes':[{'head_id':'HEAD-LJ-X8900','reference_distance':n(980,'mm','reference plane'),'nearest_z':n(-400,'mm','relative to reference'),'farthest_z':n(400,'mm','relative to reference'),'x_widths':[n(300,'mm','near side'),n(510,'mm','reference distance'),n(720,'mm','far side')],'source_evidence':[e]}]})
 put(O/'hardware/head_selection_rules.yaml',{'knowledge_status':'DERIVED','rules':[{'rule_id':'select-by-envelope','inputs':['required_z_range','required_x_width','required_working_distance','mode'],'canonical_sources':['hardware/head_specifications.yaml'],'output':'candidate heads only when canonical scoped values satisfy all inputs'}]})
 put(O/'hardware/installation_calculator_schema.yaml',{'inputs':['head_model','required_nearest_surface','required_farthest_surface','required_depth','required_x_width'],'outputs':['head_reference_position','distance_to_nearest','distance_to_farthest','available_x_widths','within_valid_envelope','margin'],'source':'canonical geometry only'})
 (O/'hardware/HEAD_COMPARISON.md').write_text('# Head comparison\n\n| Head | Controller | Ref distance | Z range | X near/ref/far | Points | Modes |\n|---|---|---:|---:|---:|---:|---|\n| LJ-X8900 | LJ-X8000 | 980 mm | Â±400 mm | 300 / 510 / 720 mm | 3200 | 2D |\n',encoding='utf8')
 ctx=json.loads((O/'routing/context_schema.yaml').read_text(encoding='utf8'));ctx['head_dependent_policy']={'require':['controller_family','head_model'],'unknown_head':'ask for exact head model'};put(O/'routing/context_schema.yaml',ctx)
 routes=json.loads((O/'routing/routing_map.yaml').read_text(encoding='utf8'));have={z['intent'] for z in routes['intent_families']}
 for i in ['head_compatibility','head_specifications','working_distance','measurement_range','field_of_view','head_selection','installation_geometry','accuracy','profile_points']:
  if i not in have:routes['intent_families'].append({'intent':i,'required_context':['controller_family','head_model'],'canonical_targets':['hardware/head_specifications.yaml','hardware/controller_head_compatibility.yaml','hardware/installation_envelopes.yaml']})
 put(O/'routing/routing_map.yaml',routes)
 sc=json.loads((O/'routing/skill_scenarios.yaml').read_text(encoding='utf8'));base=len(sc['scenarios']);qs=['LJ-X8900 Z range','required depth','installation distance','far-plane field of view','profile points','head compatibility','largest X range']
 for i,qtext in enumerate(qs,1):sc['scenarios'].append({'scenario_id':f'H{i:02d}','intent':'head_specifications','required_context':['controller_family','head_model'],'route':'head_specifications','canonical_resources':['hardware/head_specifications.yaml'],'expected_answer_components':['scoped values','source applicability'],'unsafe_assumptions_to_avoid':['do not use FOV without Z position']})
 put(O/'routing/skill_scenarios.yaml',sc)
 (O/'agent/agent_upgrade_requirements.md').write_text((O/'agent/agent_upgrade_requirements.md').read_text(encoding='utf8')+'\nHardware: always distinguish controller and head; present head values with conditions; give FOV by Z position; do not equate catalog repeatability with application accuracy; require source-grounded compatibility.\n',encoding='utf8')
 print(json.dumps({'heads_discovered':len(heads),'exact_specs':1,'source_blocks':1,'scenarios_added':len(sc['scenarios'])-base}))
if __name__=='__main__':main()

