"""Build the first LJ-X8000 operational workflow layer from canonical records."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2];O=R/'skill_data'
def put(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def step(i,action,*,commands=(),signals=(),flows=(),status='OFFICIAL_EXACT',classification='READ_ONLY',failure=None):
 return {'step_id':i,'action':action,'command_ref':[f'command:{x}' for x in commands],'signal_ref':[f'signal:{x}' for x in signals],'data_flow_ref':[f'flow:{x}' for x in flows],'expected_observation':None,'failure_branch':failure,'knowledge_status':status,'action_classification':classification}
def wf(i,title,purpose,ctx,steps,success,partial=False,warnings=()):
 return {'workflow_id':i,'title':title,'purpose':purpose,'applicability':{'controllers':['LJ-X8000'],'modes':None,'communication_methods':['Ethernet Non-Procedural']},'required_context':ctx,'preconditions':[],'steps':steps,'success_condition':success,'failure_routes':[],'state_changes':[],'warnings':list(warnings),'canonical_refs':[],'knowledge_status':'PARTIAL' if partial else 'COMPLETE'}
def main():
 cmd=json.loads((O/'operations/command_reference.yaml').read_text(encoding='utf8'));by={x['command']:x for x in cmd['commands']}
 classes={'PR':'READ_ONLY','RM':'READ_ONLY','PFR':'READ_ONLY','PFRF':'READ_ONLY','STR':'READ_ONLY','T1':'TRIGGER_ACTION','TE':'STATE_CHANGE','PW':'PROGRAM_CHANGE','SS':'PERSISTENT_SAVE','RS':'RESET_RECOVERY','R0':'STATE_CHANGE','S0':'STATE_CHANGE','RESET':'RESET_RECOVERY'}
 for c,x in by.items():x['safety_classification']=classes.get(c,'PARAMETER_WRITE' if c in {'DW','EXW','OE'} else 'UNRESOLVED')
 cmd['commands']=[by[x] for x in sorted(by)];put(O/'operations/command_reference.yaml',cmd)
 W=[
 wf('ljx8000-pc-first-connection','First PC connection','Connect using documented Ethernet Non-Procedural settings.',['controller','mode','communication_method'],[step('network','Configure documented controller network and Non-Procedural port.',status='OFFICIAL_EXACT'),step('connect','Open TCP connection to configured port 8500.',status='OFFICIAL_EXACT'),step('verify','Read controller Run/Setup state.',commands=['RM']),step('verify-program','Read current program.',commands=['PR'])],'RM and PR responses received',warnings=['Ping is not a Keyence requirement; use only as DERIVED_ENGINEERING_GUIDANCE.']),
 wf('ljx8000-software-trigger','Software trigger','Issue a software trigger after the observable READY precheck.',['controller','mode','program'],[step('precheck-ready','Confirm READY is ON.',signals=['READY']),step('precheck-enable','Confirm trigger path is enabled; TE is state-changing.',commands=['TE'],signals=['READY'],status='DERIVED',classification='STATE_CHANGE'),step('trigger','Send T1.',commands=['T1'],signals=['TRG','READY'],classification='TRIGGER_ACTION'),step('observe','Wait for READY to return after imaging/profile transfer.',signals=['READY'])],'READY returns; result/profile route depends on configured output',partial=True),
 wf('ljx8000-external-trigger','External trigger','Run external trigger through TRG/READY handshake.',['controller','mode','trigger_method'],[step('ready','Confirm READY is ON.',signals=['READY']),step('ext','Confirm EXT is OFF.',signals=['EXT','READY']),step('trigger','Apply TRG while READY is ON.',signals=['TRG','READY'],classification='TRIGGER_ACTION'),step('cycle','Observe READY OFF during transfer then ON.',signals=['READY'])],'READY returns after transfer',warnings=['If TRG has no effect, route READY -> EXT -> RUN -> ERROR/contextual -> trigger configuration.']),
 wf('ljx8000-read-latest-profile','Read latest profile','Read the latest 2D profile using PFR.',['controller','mode','head'],[step('request','Send PFR,h.',commands=['PFR'],classification='READ_ONLY'),step('parse','Parse PFR,n,pppp... as comma-separated ASCII values; invalid value is defined by canonical PFR record.',commands=['PFR'],classification='READ_ONLY')],'PFR response parsed',warnings=['Latest-profile buffering semantics remain unresolved.']),
 wf('ljx8000-fast-profile-read','Fast profile read','Read latest 2D profile using PFRF.',['controller','mode','head','trigger_method'],[step('request','Select documented PFRF request form.',commands=['PFRF']),step('parse','Parse canonical PFRF response.',commands=['PFRF'])],'PFRF response parsed',warnings=['In Continuous Trigger use 500 Hz or lower; background-buffer overflow warning applies.']),
 wf('ljx8000-switch-program','Switch program','Change active inspection program and verify read-back.',['controller','program'],[step('precheck','Read current program.',commands=['PR']),step('switch','Send PW,d,nnn.',commands=['PW'],classification='PROGRAM_CHANGE'),step('verify','Read PR again and compare requested values.',commands=['PR'])],'PR matches requested card/program',warnings=['SS is a separate persistent-save action, not an automatic switch step.']),
 wf('ljx8000-verify-current-program','Verify current program','Read active SD card/program.',['controller'],[step('read','Send PR.',commands=['PR'])],'PR response available'),
 wf('ljx8000-acquire-measurement-result','Acquire measurement result','Use configured result output only after measurement completion.',['controller','output_configuration'],[step('trigger-cycle','Use selected trigger workflow.',signals=['READY']),step('result','Read configured result output.',status='OFFICIAL_EXACT')],'Configured result received',partial=True,warnings=['Exact shared-connection parser contract for asynchronous result versus command response is unresolved.']),
 wf('ljx8000-external-string-correlation','External string correlation','Read externally specified string where configured.',['controller','string_index'],[step('read','Send STR,n.',commands=['STR'])],'STR response received',partial=True,warnings=['Write/result-output correlation is unresolved in this workflow.']),
 wf('ljx8000-reset-recovery','Reset and recovery','Recover with physical RESET or RS without treating them as equivalent.',['controller','recovery_path'],[step('physical-reset','Use documented physical RESET path if selected.',signals=['RESET','READY','BUSY'],classification='RESET_RECOVERY'),step('command-reset','Use RS only if communication reset is selected.',commands=['RS'],classification='RESET_RECOVERY'),step('verify','Recheck Run/Setup and active program.',commands=['RM','PR'])],'READY/state recovered where applicable'),
 wf('ljx8000-reconnect-after-tcp-loss','Reconnect after TCP loss','Derived client recovery pattern.',['controller'],[step('reconnect','Reconnect socket.',status='DERIVED',classification='READ_ONLY'),step('state','Re-read RM and PR; do not reuse stale result data.',commands=['RM','PR'],status='DERIVED')],'Fresh state read after reconnect',partial=True,warnings=['DERIVED_ENGINEERING_GUIDANCE; stale-result handling is not an official Keyence fact.']),]
 put(O/'workflows/operational_workflows.yaml',{'schema_version':1,'workflows':W})
 states={'model_type':'derived_operational_model','states':[{'state_id':'CONNECTED','observation':'TCP connection established','knowledge_status':'DERIVED'},{'state_id':'RUNNING','observation':'RUN output or RM reports Run','knowledge_status':'OFFICIAL_EXACT','canonical_refs':['signal:RUN','command:RM']},{'state_id':'READY','observation':'READY ON','knowledge_status':'OFFICIAL_EXACT','canonical_refs':['signal:READY']},{'state_id':'TRIGGER_ACCEPTED','observation':'READY changes OFF after accepted trigger','knowledge_status':'OFFICIAL_EXACT','canonical_refs':['signal:READY','signal:TRG']},{'state_id':'MEASUREMENT_IN_PROGRESS','observation':'BUSY or documented timing context','knowledge_status':'OFFICIAL_EXACT','canonical_refs':['signal:BUSY']},{'state_id':'RESULT_AVAILABLE','observation':'configured output complete','knowledge_status':'DERIVED','canonical_refs':['signal:STO','signal:OUT_DATA[15:0]']},{'state_id':'NOT_READY','observation':'READY OFF','knowledge_status':'OFFICIAL_EXACT','canonical_refs':['signal:READY']}]} ;put(O/'workflows/derived_operational_model.yaml',states)
 routes=json.loads((O/'routing/routing_map.yaml').read_text(encoding='utf8'));e={x['intent'] for x in routes['intent_families']}
 for x in W:
  intent=x['workflow_id'].replace('ljx8000-','').replace('-','_')
  if intent not in e:routes['intent_families'].append({'intent':intent,'required_context':x['required_context'],'canonical_targets':[f'workflows/operational_workflows.yaml#{x["workflow_id"]}']})
 put(O/'routing/routing_map.yaml',routes)
 sc=[{'scenario_id':f'S{i:02d}','intent':x['workflow_id'],'required_context':x['required_context'],'route':x['workflow_id'].replace('ljx8000-','').replace('-','_'),'canonical_resources':['workflows/operational_workflows.yaml'],'expected_answer_components':['applicability','precheck','steps','warnings'],'unsafe_assumptions_to_avoid':['do not generalize to LJ-S8000/LJ-X8000A','do not treat unresolved output framing as exact']} for i,x in enumerate(W,1)] ;put(O/'routing/skill_scenarios.yaml',{'scenarios':sc})
 (O/'routing/fallback_policy.md').write_text('# Raw corpus fallback\n\nWhen canonical workflow/knowledge lacks a requested detail, retrieve only targeted raw corpus evidence. Keep the result contextual unless direct evidence supports an exact fact, and never generalize across controller families.\n',encoding='utf8')
 guide=['# LJ-X8000 operations guide','']+[f"## {x['title']}\n\n{x['purpose']}\n" for x in W];(O/'workflows/LJX8000_OPERATIONS_GUIDE.md').write_text('\n'.join(guide),encoding='utf8')
 (O/'operations/pc_integration.yaml').write_text(json.dumps({'workflow_layer':['ljx8000-pc-first-connection','ljx8000-software-trigger','ljx8000-read-latest-profile','ljx8000-fast-profile-read','ljx8000-switch-program','ljx8000-reconnect-after-tcp-loss'],'canonical_workflow_reference':'workflows/operational_workflows.yaml'},indent=2)+'\n',encoding='utf8')
 (O/'operations/pc_integration.md').write_text('# PC integration\n\nUse the workflow layer for CONNECT, VERIFY, CONTROL, TRIGGER, READ PROFILE, PROGRAM SWITCH and RECOVER. Commands remain canonical in `operations/command_reference.yaml`; follow PRECHECK -> ACTION -> OBSERVE -> VERIFY.\n',encoding='utf8')
 ids=['pc-cannot-connect','command-no-response','command-nack','trigger-ignored','READY-off','controller-not-running','error-active','measurement-does-not-start','profile-read-fails','program-switch-fails','wrong-program-active','result-not-produced']
 play={'playbooks':[{'playbook_id':i,'canonical_targets':['operations/io_signal_reference.yaml','operations/signal_relations.yaml','operations/trigger_methods.yaml','workflows/operational_workflows.yaml'],'knowledge_status':'OFFICIAL_EXACT' if i in {'trigger-ignored','READY-off','controller-not-running','measurement-does-not-start'} else 'PARTIAL'} for i in ids]};put(O/'diagnostics/troubleshooting_playbooks.yaml',play)
 (O/'agent/agent_upgrade_requirements.md').write_text('# Agent upgrade requirements\n\nDetermine controller family and communication path; prefer read-only prechecks; warn before state-changing actions; use PRECHECK -> ACTION -> OBSERVE -> VERIFY; distinguish command responses, result output and profile data; use READY/TRG relations; disclose uncertainty where exact evidence is absent.\n',encoding='utf8')
 print(json.dumps({'workflows':len(W),'complete':sum(x['knowledge_status']=='COMPLETE' for x in W),'partial':sum(x['knowledge_status']=='PARTIAL' for x in W)}))
if __name__=='__main__':main()
