"""Normalize all columns of the visually verified LJ-X head specification table."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2];O=R/'skill_data'
def put(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
def main():
 bpath=O/'evidence/manual_source_blocks/MSB-LJX8000-379-X8900-SPECS.json';b=json.loads(bpath.read_text(encoding='utf8'));models=['LJ-X8020','LJ-X8030','LJ-X8060','LJ-X8070','LJ-X8080','LJ-X8100','LJ-X8200','LJ-X8300','LJ-X8400','LJ-X8900'];b['model_columns']=models;b['row_labels']=['Reference distance','Z-axis height','X-axis width near/reference/far','Repeatability Z/X','Linearity','Profile data interval','Profile data count','Wavelength','Laser class','IP rating','Ambient temperature'];b['visual_verified']=True;put(bpath,b)
 e={'evidence_quality':'DIRECT_VISUAL','block_id':b['block_id'],'document_id':b['document_id'],'source_sha256':b['source_sha256'],'pdf_page_index':379,'printed_page':'10-5','evidence_excerpt_hash':b['native_text_sha256']}
 refs=[20,28,64,50,73,107,245,288,380,980];z=[(-2.2,2.2),(-6.5,6.5),(-7.3,7.3),(-8,8),(-20.5,20.5),(-17,17),(-34,34),(-53,53),(-220,95),(-400,400)];xs=[(7,7.5,8),(16,16,16),(15,16,16),(33.5,35,36.5),(30,35,39),(71,74,77),(64,72,80),(134,150,160),(180,210,240),(300,510,720)];rz=[.3,.3,.4,.3,.5,.5,1,3,5,10];rx=[.3,.5,.5,1,1,3,3,5,10,25];interval=[2.5,5,5,12.5,12.5,25,25,50,75,225];interval_condition=['from 2 um','from 3 um','from 4 um','from 10 um','from 10 um','from 20 um','from 20 um','from 40 um','from 50 um; source table also lists 100 um with footnote *11','from 100 um']
 cond={'conditions':[{'condition_id':'COND-REPEATABILITY','text':'Measured object is a standard object determined by Keyence; value when measuring average height of initial setting area with height/position tool; other settings initial settings.','applies_to':['repeatability_z','repeatability_x'],'heads':models,'source_evidence':[e]},{'condition_id':'COND-PROFILE-INTERVAL','text':'Profile data interval is changeable; changing it changes X-direction measurement range accordingly.','applies_to':['x_resolution'],'heads':models,'source_evidence':[e]}]};put(O/'hardware/head_spec_conditions.yaml',cond)
 def n(v,u,scope,condition='COND-REPEATABILITY'):return {'value':v,'unit':u,'condition_ref':condition,'scope':scope,'mode':'2D','evidence':[e]}
 heads=[];env=[]
 for i,m in enumerate(models):
  lo,hi=z[i];near,ref,far=xs[i];full=hi-lo
  h={'head_id':'HEAD-'+m,'model':m,'family':'LJ-X Series','compatible_controllers':[{'controller':'LJ-X8000','head':'HEAD-'+m,'relation':'NOT_VERIFIED' if m!='LJ-X8900' else 'COMPATIBLE','mode':'2D','direct_evidence':[e] if m=='LJ-X8900' else []}],'optical_geometry':{'z_coordinate_convention':{'source_mapping':'Z-axis values are relative to reference distance; physical near/far envelope uses the numerical minimum/maximum of reference plus listed Z bounds.','evidence':[e]},'reference_distance':n(refs[i],'mm','reference distance','SOURCE_TABLE'),'measurement_distance_range':{'lower_z_relative':n(lo,'mm','listed Z lower bound','SOURCE_TABLE'),'reference_z':n(0,'mm','reference','SOURCE_TABLE'),'upper_z_relative':n(hi,'mm','listed Z upper bound','SOURCE_TABLE')},'z_range':n(full,'mm','full scale','SOURCE_TABLE'),'x_range_at_near':n(near,'mm','near side','SOURCE_TABLE'),'x_range_at_reference':n(ref,'mm','reference distance','SOURCE_TABLE'),'x_range_at_far':n(far,'mm','far side','SOURCE_TABLE'),'intermediate_fov_policy':'NOT_DEFINED'},'sampling':{'profile_points':n(3200,'points','shared table row for all listed models','SOURCE_TABLE'),'profile_data_interval':n(interval[i],'um',interval_condition[i],'COND-PROFILE-INTERVAL')},'metrology':{'repeatability_z':n(rz[i],'um','Z-axis height','COND-REPEATABILITY'),'repeatability_x':n(rx[i],'um','X-axis width','COND-REPEATABILITY'),'linearity':{'value':None,'status':'NOT_VERIFIED'}},'optics':{'wavelength':n(405,'nm','visible light; shared table row','SOURCE_TABLE'),'laser_class':{'value':'Class 3R laser product' if m=='LJ-X8030' else 'Class 2M laser product','evidence':[e]}},'environment':{'protection_rating':{'value':'IP67 (IEC60529)','evidence':[e]},'operating_temperature':n('0 to +45','C','ambient temperature; shared table row','SOURCE_TABLE')},'installation':{'reference_distance':n(refs[i],'mm','reference plane','SOURCE_TABLE'),'interpolation_policy':'NOT_DEFINED'},'modes':['2D'],'limitations':['Use source-defined near/reference/far X widths; intermediate FOV is not defined.'],'source_evidence':[e]}
  if m=='LJ-X8400':
   h['sampling']['profile_data_interval']['alternative_source_value']=n(100,'um','from 50 um; table footnote *11','COND-PROFILE-INTERVAL')
   h['sampling']['profile_data_interval']['alternative_status']='SOURCE_TABLE_ALTERNATIVE'
  heads.append(h);env.append({'head_id':h['head_id'],'reference_distance':h['optical_geometry']['reference_distance'],'nearest_surface_distance':{'value':refs[i]+min(lo,hi),'unit':'mm','knowledge_status':'DERIVED','canonical_refs':['optical_geometry.reference_distance','optical_geometry.measurement_distance_range.lower_z_relative']},'farthest_surface_distance':{'value':refs[i]+max(lo,hi),'unit':'mm','knowledge_status':'DERIVED','canonical_refs':['optical_geometry.reference_distance','optical_geometry.measurement_distance_range.upper_z_relative']},'z_range':h['optical_geometry']['z_range'],'x_width_near':h['optical_geometry']['x_range_at_near'],'x_width_reference':h['optical_geometry']['x_range_at_reference'],'x_width_far':h['optical_geometry']['x_range_at_far'],'interpolation_policy':'NOT_DEFINED'})
 put(O/'hardware/head_specifications.yaml',{'heads':heads});put(O/'hardware/installation_envelopes.yaml',{'envelopes':env});put(O/'hardware/controller_head_compatibility.yaml',{'relationships':[{'controller':'LJ-X8000','head':'HEAD-'+m,'relation':'COMPATIBLE' if m=='LJ-X8900' else 'NOT_VERIFIED','mode':'2D' if m=='LJ-X8900' else 'unknown','direct_evidence':[e] if m=='LJ-X8900' else []} for m in models]})
 put(O/'hardware/head_capability_matrix.yaml',{'heads':models,'properties':{h['model']:{'reference_distance':h['optical_geometry']['reference_distance']['value'],'z_full_range':h['optical_geometry']['z_range']['value'],'x_near_reference_far':[h['optical_geometry'][k]['value'] for k in ['x_range_at_near','x_range_at_reference','x_range_at_far']],'profile_points':3200,'profile_data_interval':h['sampling']['profile_data_interval']['value'],'repeatability_z':h['metrology']['repeatability_z']['value'],'repeatability_x':h['metrology']['repeatability_x']['value'],'laser_class':h['optics']['laser_class']['value'],'ip':'IP67'} for h in heads}})
 lines=['# Head comparison','', '| Model | Ref distance | Z full | X near | X reference | X far | Points | Z repeatability | X repeatability | Laser | IP |','|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---|']
 for h in heads: g=h['optical_geometry'];lines.append(f"| {h['model']} | {g['reference_distance']['value']} mm | {g['z_range']['value']} mm | {g['x_range_at_near']['value']} mm | {g['x_range_at_reference']['value']} mm | {g['x_range_at_far']['value']} mm | 3200 | {h['metrology']['repeatability_z']['value']} um | {h['metrology']['repeatability_x']['value']} um | {h['optics']['laser_class']['value']} | IP67 |")
 (O/'hardware/HEAD_COMPARISON.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
 put(O/'hardware/head_selection_rules.yaml',{'knowledge_status':'DERIVED','safety_rule':'Catalog repeatability only evaluates the documented condition; it does not predict application accuracy.','filters':['required_z_range','required_x_width_at_near','required_x_width_at_reference','required_x_width_at_far','minimum_working_distance','maximum_working_distance','repeatability_requirement','profile_point_requirement'],'missing_spec_policy':'never treat missing data as zero or compatible'})
 print(json.dumps({'heads':len(heads),'complete_geometry':len(heads),'conditions':2}))
if __name__=='__main__':main()





